# Generated by Django 2.2.4 on 2023-03-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_events_app', '0010_auto_20230302_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
