# Generated by Django 2.2.4 on 2023-03-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood_events_app', '0011_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
